import adiddas from '../images/adidas.svg'
import amazon from '../images/Amazon.png'
import amex from '../images/Amex.jfif'
import bestBuy from '../images/best-buy.jpg'
import eBay from '../images/e-bay.jpg'
import finishLine from '../images/finish-line.png'
import footLocker from '../images/foot-locker.jfif'
import g2a from '../images/g2a.jpg'
import gameStop from '../images/game-stop.png'
import googlePlay from '../images/google play.png'
import greenDot from '../images/green-dot.png'
import happy from '../images/happy.png'
import homeDepot from '../images/home-depot.png'
import hotels from '../images/hotels.jfif'
import iTunes from '../images/itunes.jfif'
import jcpenny from '../images/jcpenny.jpg'
import lowes from '../images/lowes.jpg'
import macys from "../images/macy's.jpg"
import netflix from '../images/netflix.jpg'
import nike from '../images/Nike.jpg'
import nordstrom from '../images/nordstrom.jpg'
import offGamers from '../images/offGamers.png'
import playStation from '../images/play-station.jfif'
import razerGold from '../images/razer_gold.png'
import sephora from '../images/Sephora.png'
import starBuck from '../images/star-buck.jfif'
import steam from '../images/Steam.jfif'
import target from '../images/target.jfif'
import targetVisa from '../images/target-visa.jpg'
import uber from '../images/uber.jpg'
import vanilla from '../images/vanilla.jfif'
import visa from '../images/visa.jpg'
import walmart from '../images/walmart.jfif'
import walmartVisa from '../images/walmart-visa.jfif'
import xbox from '../images/xbox.jfif'



export const allGiftCards = [
    {
      id: "1",
      title: "Steam",
      img: steam,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "2",
      title: "Apple Universal",
      img: uber,
      currencies: ["usd", "gbp", "eur", "aud", "cad", "nzd", "chf"],
    },
    {
      id: "3",
      title: "iTunes",
      img: iTunes,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "grc",
        "prt",
        "nld",
        "bel",
        "fin",
        "sgd",
        "ger",
        "aut",
        "fra",
        "itl",
        "esp",
        "irl",
        "hkd",
        "dmk",
        "pln",
        "rub",
        "tur",
        "brl",
        "nok",
        "swe",
        "zar",
        "mxn",
        "twd",
        "jpy",
      ],
    },
    {
      id: "4",
      title: "Google Play",
      img: googlePlay,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "sgd",
        "jpy",
        "brl",
        "pln",
        "mxn",
        "zar",
        "hkd",
        "idr",
        "thb",
        "myr",
        "tur",
        "krw",
      ],
    },
    {
      id: "5",
      title: "Amazon",
      img: amazon,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "6",
      title: "Ebay",
      img: eBay,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "7",
      title: "Sephora",
      img: sephora,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "8",
      title: "American Express",
      img: amex,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "9",
      title: "Vanilla",
      img: vanilla,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "10",
      title: "Walmart",
      img: walmart,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "11",
      title: "Nordstrom",
      img: nordstrom,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "12",
      title: "Target",
      img: target,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "13",
      title: "Offgamers",
      img: offGamers,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "14",
      title: "Xbox",
      img: xbox,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "15",
      title: "Macy’s",
      img: macys,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "16",
      title: "Razer Gold",
      img: razerGold,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "17",
      title: "JCPenny",
      img: jcpenny,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "18",
      title: "Foot Locker",
      img: footLocker,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "19",
      title: "Nike",
      img: nike,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "20",
      title: "Visa",
      img: visa,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "21",
      title: "Target Visa",
      img: targetVisa,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "22",
      title: "Walmart Visa",
      img: walmartVisa,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "23",
      title: "Greendot",
      img: greenDot,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "24",
      title: "Best Buy ",
      img: bestBuy,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "25",
      title: "Play Station",
      img: playStation,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "26",
      title: "Home Depot",
      img: homeDepot,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "27",
      title: "Starbucks",
      img: starBuck,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "28",
      title: "Netflix",
      img: netflix,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "29",
      title: "Happy",
      img: happy,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "30",
      title: "Lowe’s",
      img: lowes,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "31",
      title: "Gamestop",
      img: gameStop,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "32",
      title: "Uber",
      img: uber,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "33",
      title: "Adiddas",
      img: adiddas,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "34",
      title: "G2A",
      img: g2a,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "35",
      title: "Hotels",
      img: hotels,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
    {
      id: "36",
      title: "Finish Line",
      img: finishLine,
      currencies: [
        "usd",
        "gbp",
        "eur",
        "aud",
        "cad",
        "nzd",
        "chf",
        "brl",
        "pol",
        "hkd",
      ],
    },
  ];
  